# ============================================================================
# Layer Definitions (圖層類型定義)
# Based on all_att.txt
# ============================================================================

baseLayer = {
    "Watch name": "str",
    "Discription": "str",
    "Background": "color",
    "Tags": "str",
    "Shape": ["Circle", "Square", "Apple"],
    "Author": "str",
    "Web link": "str",
    "Transition to bright": ["None"],
    "Transition to dim": ["None"],
    "Script": "script",
    "Indicators": "str",
}

# Animation Widget (動畫控制器)
animationWidget = {
    "Animation in": ["None", "test"],
    "Delay start": (1, 2048, 0),
    "Duration in": (1, 2048, 0),
    "Duration on": (1, 2048, 0),
    "Animation out": ["None"],
    "Duration out": (1, 2048, 0),
    "Duration off": (1, 2048, 0),
    "Repeat count": [1],
    "Restart on load": "bool",
    "Restart on bright": "bool",
    "Restart on text change": "bool",
}

# Text Layer (文字圖層)
textLayer = {
    "Name": "str",
    "Layer": (0, 5000, 1),
    "Text": "text",
    "X": (-1280, 1280, 0),
    "Y": (-1280, 1280, 0),
    "Animation": "widget",
    "Gyro effect": (1, 2048, 0),
    "Font": "font",
    "Text size": (1, 2048, 0),
    "Color": "color",
    "Color dim": "color",
    "Anim scale X": (-2048, 2048, 0),
    "Anim scale Y": (-2048, 2048, 0),
    "Rotation": (-720, 720, 0),
    "Skew X": (0, 90, 0),
    "Skew Y": (0, 90, 0),
    "Opacity": (0, 100, 0),
    "Alignment": [
        "Center",
        "Top left",
        "Top center",
        "Top right",
        "Center left",
        "Center right",
        "Bottom left",
        "Bottom center",
        "Bottom right",
    ],
    "Transform": ["None"],
    "Display": ["Always", "Bright only", "Dimmed only", "Never"],
    "Shader": ["None"],
    "Tap action": ["None"],
    "Text effect": ["None"],
    "Keep position if card displayed": "bool",
}

# Directional Light Layer (方向光源圖層)
directionalLightLayer = {
    "Name": "str",
    "Enable": "bool",
    "Intensity": (1, 2048, 0),
    "Direction X": (1, 2048, 0),
    "Direction Y": (1, 2048, 0),
    "Direction Z": (1, 2048, 0),
    "Color": "color",
}

# 3D Layer (3D圖層)
layer3D = {
    "Name": "str",
    "Layer": (0, 5000, 1),
    "Photo": "file",
    "X": (-1280, 1280, 0),
    "Y": (-1280, 1280, 0),
    "Z": (-1280, 1280, 0),
    "Rotation X": (-720, 720, 0),
    "Rotation Y": (-720, 720, 0),
    "Rotation Z": (-720, 720, 0),
    "Scale X": (1, 2048, 0),
    "Scale Y": (1, 2048, 0),
    "Scale Z": (1, 2048, 0),
    "Gyro effect": (1, 2048, 0),
    "Opacity": (0, 100, 0),
    "Color": "color",
    "Display": ["Always", "Bright only", "Dimmed only", "Never"],
}

# Curved Text Layer (曲線文字圖層) - inherits from textLayer
curvedTextLayer = {
    "Name": "str",
    "Layer": (0, 5000, 1),
    "Text": "text",
    "X": (-1280, 1280, 0),
    "Y": (-1280, 1280, 0),
    "Animation": "widget",
    "Gyro effect": (1, 2048, 0),
    "Font": "font",
    "Text size": (1, 2048, 0),
    "Color": "color",
    "Color dim": "color",
    "Anim scale X": (-2048, 2048, 0),
    "Anim scale Y": (-2048, 2048, 0),
    "Rotation": (-720, 720, 0),
    "Skew X": (0, 90, 0),
    "Skew Y": (0, 90, 0),
    "Opacity": (0, 100, 0),
    "Radius": (1, 2048, 0),
    "Direction": ["Up", "Down"],
    "Alignment": [
        "Center",
        "Top left",
        "Top center",
        "Top right",
        "Center left",
        "Center right",
        "Bottom left",
        "Bottom center",
        "Bottom right",
    ],
    "Transform": ["None"],
    "Display": ["Always", "Bright only", "Dimmed only", "Never"],
    "Shader": ["None"],
    "Tap action": ["None"],
    "Text effect": ["None"],
    "Keep position if card displayed": "bool",
}

# Image Layer (圖片圖層) - inherits from textLayer
imageLayer = {
    "Name": "str",
    "Layer": (0, 5000, 1),
    "X": (-1280, 1280, 0),
    "Y": (-1280, 1280, 0),
    "Gyro effect": (1, 2048, 0),
    "Width": (1, 2048, 0),
    "Height": (1, 2048, 0),
    "Rotation": (-720, 720, 0),
    "Skew X": (0, 90, 0),
    "Skew Y": (0, 90, 0),
    "Opacity": (0, 100, 0),
    "Tint": "color",
    "Alignment": [
        "Center",
        "Top left",
        "Top center",
        "Top right",
        "Center left",
        "Center right",
        "Bottom left",
        "Bottom center",
        "Bottom right",
    ],
    "Display": ["Always", "Bright only", "Dimmed only", "Never"],
    "Shader": ["None"],
    "Tap action": ["None"],
    "Custom image": "file",
    "Keep position if card displayed": "bool",
}

# Tachymeter Layer (測速計圖層) - inherits from curvedTextLayer
tachymeterLayer = {
    "Name": "str",
    "Layer": (0, 5000, 1),
    "Text": "text",
    "X": (-1280, 1280, 0),
    "Y": (-1280, 1280, 0),
    "Gyro effect": (1, 2048, 0),
    "Font": "font",
    "Text size": (1, 2048, 0),
    "Color": "color",
    "Color dim": "color",
    "Anim scale X": (-2048, 2048, 0),
    "Anim scale Y": (-2048, 2048, 0),
    "Radius": (1, 2048, 0),
    "Rotation": (-720, 720, 0),
    "Skew X": (0, 90, 0),
    "Skew Y": (0, 90, 0),
    "Opacity": (0, 100, 0),
    "Alignment": [
        "Center",
        "Top left",
        "Top center",
        "Top right",
        "Center left",
        "Center right",
        "Bottom left",
        "Bottom center",
        "Bottom right",
    ],
    "Transform": ["None"],
    "Marker width": (1, 2048, 1),
    "Marker height": (1, 2048, 1),
    "Major markers": [
        "None",
        "Tiny",
        "Small",
        "Medium",
        "Large",
        "XLarge",
        "Circle",
        "Triangle",
    ],
    "Minor markers": [
        "None",
        "Tiny",
        "Small",
        "Medium",
        "Large",
        "XLarge",
        "Circle",
        "Triangle",
    ],
    "Speeds": [
        "400,300,240,200,180,160,140,120,110,95,90,85,80,75,70,65,60",
        "400,300,240,200,180,160,140,120,110,90,80,75,70,65,60",
        "320,250,200,180,160,140,120,110,90,80,75,70,65,60",
        "300,240,200,150,135,120,110,90,80,75,70,65,60",
        "300,240,200,160,140,120,100,90,80,70,60",
        "Custom"
        ],
    "Custom speeds": "str",
    "Text rotation": [
        "Upright",
        "Rotate",
        "Rotate Inverse",
        "Rotate Upright",
    ],
    "Squarify": (1, 100, 1),
    "Display": ["Always", "Bright only", "Dimmed only", "Never"],
    "Tap action": ["None"],
    "Text effect": ["None"],
    "Keep position if card displayed": "bool",
}

# Shape Layer (形狀圖層)
shapeLayer = {
    "Name": "str",
    "Layer": (0, 5000, 1),
    "Shape": ["Square","Circle","Triangle","Pentagon","Hexagon","Star","Heart"],
    "X": (-1280, 1280, 0),
    "Y": (-1280, 1280, 0),
    "Gyro effect": (1, 2048, 0),
    "Width": (1, 2048, 0),
    "Height": (1, 2048, 0),
    "Rotation": (-720, 720, 0),
    "Skew X": (0, 90, 0),
    "Skew Y": (0, 90, 0),
    "Opacity": (0, 100, 0),
    "Alignment": [
        "Center",
        "Top left",
        "Top center",
        "Top right",
        "Center left",
        "Center right",
        "Bottom left",
        "Bottom center",
        "Bottom right",
    ],
    "Color": "color",
    "Display": ["Always", "Bright only", "Dimmed only", "Never"],
    "Shader": ["None"],
    "Tap action": ["None"],
    "Shape effect": ["None"],
}

# Marker Layer (標記圖層)
markerLayer = {
    "Name": "str",
    "Layer": (0, 5000, 1),
    "X": (-1280, 1280, 0),
    "Y": (-1280, 1280, 0),
    "Gyro effect": (1, 2048, 0),
    "Color": "color",
    "Anim scale X": (-2048, 2048, 0),
    "Anim scale Y": (-2048, 2048, 0),
    "Radius": (1, 2048, 0),
    "Rotation": (-720, 720, 0),
    "Skew X": (0, 90, 0),
    "Skew Y": (0, 90, 0),
    "Opacity": (0, 100, 0),
    "Transform": ["None"],
    "Marker width": (1, 50, 1),
    "Marker height": (1, 50, 1),
    "Marker count": (1, 360, 1),
    "Shape": [
        "Square",
        "Circle",
        "Triangle"
    ],
    "Squarify": (0, 100, 1),
    "Display": ["Always", "Bright only", "Dimmed only", "Never"],
    "Tap action": ["None"],
    "Text effect": ["None"],
}

# Map Layer (地圖圖層) - inherits from imageLayer
mapLayer = {
    "X": (-1280, 1280, 0),
    "Y": (-1280, 1280, 0),
    "Gyro effect": (1, 2048, 0),
    "Width": (1, 2048, 0),
    "Height": (1, 2048, 0),
    "Rotation": (-720, 720, 0),
    "Skew X": (0, 90, 0),
    "Skew Y": (0, 90, 0),
    "Opacity": (0, 100, 0),
    "Latitude": (1, 2048, 0),
    "Longitude": (1, 2048, 0),
    "Map zoom": (1, 2048, 0),
    "Map scale": (1, 2048, 0),
    "Tint": "color",
    "Alignment": [
        "Center",
        "Top left",
        "Top center",
        "Top right",
        "Center left",
        "Center right",
        "Bottom left",
        "Bottom center",
        "Bottom right",
    ],
    "Display": ["Always", "Bright only", "Dimmed only", "Never"],
    "Shader": ["None"],
    "Tap action": ["None"],
    "Map effect": ["None"],
}

# Slideshow Layer (幻燈片圖層) - inherits from imageLayer
slideshowLayer = {
    "Name": "str",
    "Layer": (0, 5000, 1),
    "Photo": "files",
    "Photo duration": (1, 2048, 1),
    "Photo clip": [
        "None",
        "Circle",
        "Corner 1",
        "Corner 2",
    ],
    "X": (-1280, 1280, 0),
    "Y": (-1280, 1280, 0),
    "Gyro effect": (1, 2048, 0),
    "Width": (1, 2048, 0),
    "Height": (1, 2048, 0),
    "Rotation": (-720, 720, 0),
    "Skew X": (0, 90, 0),
    "Skew Y": (0, 90, 0),
    "Opacity": (0, 100, 0),
    "Tint": "color",
    "Alignment": [
        "Center",
        "Top left",
        "Top center",
        "Top right",
        "Center left",
        "Center right",
        "Bottom left",
        "Bottom center",
        "Bottom right",
    ],
    "Display": ["Always", "Bright only", "Dimmed only", "Never"],
    "Shader": ["None"],
    "Tap action": ["None"],
    "Keep position if card displayed": "bool",
}

# Text Ring Layer (環形文字圖層) - inherits from textLayer
textRingLayer = {
    "Name": "str",
    "Layer": (0, 5000, 1),
    "X": (-1280, 1280, 0),
    "Y": (-1280, 1280, 0),
    "Gyro effect": (1, 2048, 0),
    "Font": "font",
    "Text size": (1, 2048, 0),
    "Color": "color",
    "Color dim": "color",
    "Anim scale X": (-2048, 2048, 0),
    "Anim scale Y": (-2048, 2048, 0),
    "Rotation": (-720, 720, 0),
    "Skew X": (0, 90, 0),
    "Skew Y": (0, 90, 0),
    "Opacity": (0, 100, 0),
    "Transform": ["None"],
    "Display": ["Always", "Bright only", "Dimmed only", "Never"],
    "Radius": (1, 2048, 0),
    "Ring type": [
        "1-12",
        "1-24",
        "1-30",
        "1-31",
        "1-60",
        "1-100",
        "Custom (x to y)",
        "I-XII",
        "Mo-Su",
        "Mon-Sun",
        "Jan-Dec",
    ],
    "Custom start": (-2048, 2048, 1),
    "Custom end": (-2048, 2048, 12),
    "Show every": (1, 2048, 1),
    "Hide text": "str",
    "Text rotation": [
        "Upright",
        "Rotate",
        "Rotate Inverse",
        "Rotate Upright",
    ],
    "Angle start": (1, 2048, 1),
    "Angle end": (1, 2048, 1),
    "Squarify": (1, 100, 1),
    "Shader": ["None"],
    "Tap action": ["None"],
    "Text effect": ["None"],
    "Keep position if card displayed": "bool",
}

# Rounded Rectangle Layer (圓角矩形圖層) - inherits from imageLayer
roundedRectangleLayer = {
    "X": (-1280, 1280, 0),
    "Y": (-1280, 1280, 0),
    "Gyro effect": (1, 2048, 0),
    "Width": (1, 2048, 0),
    "Height": (1, 2048, 0),
    "Corner radius": (1, 2048, 0),
    "Corner type": (1, 15, 1),
    "Rotation": (-720, 720, 0),
    "Skew X": (0, 90, 0),
    "Skew Y": (0, 90, 0),
    "Opacity": (0, 100, 0),
    "Alignment": [
        "Center",
        "Top left",
        "Top center",
        "Top right",
        "Center left",
        "Center right",
        "Bottom left",
        "Bottom center",
        "Bottom right",
    ],
    "Color": "color",
    "Display": ["Always", "Bright only", "Dimmed only", "Never"],
    "Shader": ["None"],
    "Tap action": ["None"],
    "Shape effect": ["None"],
    "Keep position if card displayed": "bool",
}

# Series Layer (數據系列圖層) - inherits from textLayer
seriesLayer = {
    "X": (-1280, 1280, 0),
    "Y": (-1280, 1280, 0),
    "Gyro effect": (1, 2048, 0),
    "Font": "font",
    "Font 2": "font",
    "Text size": (1, 2048, 0),
    "Text size 2": (1, 2048, 0),
    "Color": "color",
    "Color 2": "color",
    "Anim scale X": (-2048, 2048, 0),
    "Anim scale Y": (-2048, 2048, 0),
    "Rotation": (-720, 720, 0),
    "Skew X": (0, 90, 0),
    "Skew Y": (0, 90, 0),
    "Opacity": (0, 100, 0),
    "Alignment": [
        "Center",
        "Top left",
        "Top center",
        "Top right",
        "Center left",
        "Center right",
        "Bottom left",
        "Bottom center",
        "Bottom right",
    ],
    "Transform": ["None"],
    "Display": ["Always", "Bright only", "Dimmed only", "Never"],
    "Series type": ["Day of the week short"],
    "Orientation": ["Vertical"],
    "Current position": ["Current Centered"],
    "Spacing": (1, 2048, 0),
    "Shader": ["None"],
    "Tap action": ["None"],
    "Text effect": ["None"],
    "Keep position if card displayed": "bool",
}

# Complication Layer (複雜功能圖層) - inherits from textLayer
complicationLayer = {
    "Color text": "color",
    "Color background": "color",
    "X": (-1280, 1280, 0),
    "Y": (-1280, 1280, 0),
    "Animation": "widget",
    "Gyro effect": (1, 2048, 0),
    "Font": "font",
    "Text size": (1, 2048, 0),
    "Color": "color",
    "Color dim": "color",
    "Anim scale X": (-2048, 2048, 0),
    "Anim scale Y": (-2048, 2048, 0),
    "Rotation": (-720, 720, 0),
    "Skew X": (0, 90, 0),
    "Skew Y": (0, 90, 0),
    "Opacity": (0, 100, 0),
    "Width": (1, 2048, 0),
    "Height": (1, 2048, 0),
    "Alignment": [
        "Center",
        "Top left",
        "Top center",
        "Top right",
        "Center left",
        "Center right",
        "Bottom left",
        "Bottom center",
        "Bottom right",
    ],
    "Transform": ["None"],
    "Display": ["Always", "Bright only", "Dimmed only", "Never"],
}

# Chart Layer (圖表圖層)
chartLayer = {
    "X": (-1280, 1280, 0),
    "Y": (-1280, 1280, 0),
    "Gyro effect": (1, 2048, 0),
    "Rotation": (-720, 720, 0),
    "Skew X": (0, 90, 0),
    "Skew Y": (0, 90, 0),
    "Opacity": (0, 100, 0),
    "Width": (1, 2048, 0),
    "Height": (1, 2048, 0),
    "Color": "color",
    "Color 2": "color",
    "Color 3": "color",
    "Color 4": "color",
    "Chart type": ["line"],
    "Data points": "str",
    "Min max": "str",
    "Chart group": (1, 2048, 0),
    "Line width": (1, 2048, 0),
    "Marker size": (1, 2048, 0),
    "Tension": (1, 2048, 0),
    "Top opacity": (0, 100, 0),
    "Bottom opacity": (0, 100, 0),
    "Radius": (1, 2048, 0),
    "Bar thickness": (1, 2048, 0),
    "Corner type": (1, 2048, 1),
    "Lines": "str",
    "Labels": "str",
    "Anim scale X": (-2048, 2048, 0),
    "Anim scale Y": (-2048, 2048, 0),
    "Display": ["Always", "Bright only", "Dimmed only", "Never"],
}

# Image Condition Layer (條件圖片圖層) - inherits from textLayer
imageCondLayer = {
    "Name": "str",
    "Layer": (0, 5000, 1),
    "X": (-1280, 1280, 0),
    "Y": (-1280, 1280, 0),
    "Gyro effect": (1, 2048, 0),
    "Width": (1, 2048, 0),
    "Height": (1, 2048, 0),
    "Rotation": (-720, 720, 0),
    "Skew X": (0, 90, 0),
    "Skew Y": (0, 90, 0),
    "Opacity": (0, 100, 0),
    "Tint": "color",
    "Alignment": [
        "Center",
        "Top left",
        "Top center",
        "Top right",
        "Center left",
        "Center right",
        "Bottom left",
        "Bottom center",
        "Bottom right",
    ],
    "Display": ["Always", "Bright only", "Dimmed only", "Never"],
    "Shader": ["None"],
    "Image selection": (1, 2048, 0),
    "Image grid": ["2x2", "3x2", "3x3", "4x3", "4x4", "5x5"],
    "Tap action": ["None"],
    "Custom image": "file",
    "Weather includes night symbols": "bool",
    "Keep position if card displayed": "bool",
}

# Image GIF Layer (GIF圖片圖層)
imageGifLayer = {
    "X": (-1280, 1280, 0),
    "Y": (-1280, 1280, 0),
    "Gyro effect": (1, 2048, 0),
    "Rotation": (-720, 720, 0),
    "Skew X": (0, 90, 0),
    "Skew Y": (0, 90, 0),
    "Opacity": (0, 100, 0),
    "Alignment": [
        "Center",
        "Top left",
        "Top center",
        "Top right",
        "Center left",
        "Center right",
        "Bottom left",
        "Bottom center",
        "Bottom right",
    ],
    "Path": "str",
    "Width": (1, 2048, 0),
    "Height": (1, 2048, 0),
    "Gif delay": (1, 2048, 0),
    "Display": ["Always", "Bright only", "Dimmed only", "Never"],
}

# Progress Layer (進度條圖層)
progressLayer = {
    "X": (-1280, 1280, 0),
    "Y": (-1280, 1280, 0),
    "Gyro effect": (1, 2048, 0),
    "Rotation": (-720, 720, 0),
    "Skew X": (0, 90, 0),
    "Skew Y": (0, 90, 0),
    "Opacity": (0, 100, 0),
    "Width": (1, 2048, 0),
    "Height": (1, 2048, 0),
    "Color": "color",
    "Color 2": "color",
    "Color 3": "color",
    "Color 4": "color",
    "Outside opacity": (0, 100, 0),
    "Radius": (1, 2048, 0),
    "Pct complete": "str",
    "Angle": (1, 2048, 0),
    "Margin": (1, 2048, 0),
    "End style": ["flat"],
    "Corner type": (1, 2048, 1),
    "Anim scale X": (-2048, 2048, 0),
    "Anim scale Y": (-2048, 2048, 0),
    "Display": ["Always", "Bright only", "Dimmed only", "Never"],
}

# Ring Layer (圓環圖層)
ringLayer = {
    "X": (-1280, 1280, 0),
    "Y": (-1280, 1280, 0),
    "Gyro effect": (1, 2048, 0),
    "Rotation": (-720, 720, 0),
    "Skew X": (0, 90, 0),
    "Skew Y": (0, 90, 0),
    "Opacity": (0, 100, 0),
    "Radius outer": (1, 2048, 0),
    "Radius inner": (1, 2048, 0),
    "Radius": (1, 2048, 0),
    "Angle": (1, 2048, 0),
    "Angle total": (1, 2048, 0),
    "Is clockwise": ["Y"],
    "Color": "color",
    "Color 2": "color",
    "Color 3": "color",
    "Outside opacity": (0, 100, 0),
    "Anim scale X": (-2048, 2048, 0),
    "Anim scale Y": (-2048, 2048, 0),
    "Display": ["Always", "Bright only", "Dimmed only", "Never"],
}

# Markers HM Layer (時分標記圖層) - inherits from markerLayer
markersHMLayer = {
    "X": (-1280, 1280, 0),
    "Y": (-1280, 1280, 0),
    "Gyro effect": (1, 2048, 0),
    "Rotation": (-720, 720, 0),
    "Skew X": (0, 90, 0),
    "Skew Y": (0, 90, 0),
    "Opacity": (0, 100, 0),
    "Radius": (1, 2048, 0),
    "Anim scale X": (-2048, 2048, 0),
    "Anim scale Y": (-2048, 2048, 0),
    "Hour markers": ["Medium"],
    "Minute markers": ["Medium"],
    "Hour color": "color",
    "Minute color": "color",
    "Squarify": (1, 100, 1),
    "Display": ["Always", "Bright only", "Dimmed only", "Never"],
}

# Export all Layer definitions
__all__ = [
    "baseLayer",
    "animationWidget", #need information
    "textLayer",
    "directionalLightLayer", #incomplete
    "layer3D", #incomplete
    "curvedTextLayer",
    "imageLayer",
    "tachymeterLayer",
    "shapeLayer",
    "markerLayer",
    "mapLayer", #incomplete
    "slideshowLayer", 
    "textRingLayer", 
    "roundedRectangleLayer",
    "seriesLayer", #incomplete
    "complicationLayer", #incomplete
    "chartLayer", #need information
    "imageCondLayer",
    "imageGifLayer", #need information
    "progressLayer", #need information
    "ringLayer", #need information
    "markersHMLayer", #incomplete
]
